require_relative 'queries/import_list'
require_relative 'queries/import_cards'
require_relative 'queries/printing_details'
require_relative 'queries/printings'
require_relative 'queries/editions'
require_relative 'queries/decks'
require_relative 'queries/deck_cards'
require_relative 'queries/cards'
require_relative 'queries/deck_card_details'
require_relative 'queries/imports'
require_relative 'queries/user_printings'

require_relative 'queries/collection'
require_relative 'queries/edition_cards'
